import { lazy } from "react";
import type { IToolCategory, IToolCategoryDefinition, IToolDefinition } from "../types/toolTypes";

const textCategory: IToolCategory = "text";
const textCategoryLabel = "Text";
const imageCategory: IToolCategory = "image";
const imageCategoryLabel = "Image";
const developerCategory: IToolCategory = "developer";
const developerCategoryLabel = "Developer";
const financeCategory: IToolCategory = "finance";
const financeCategoryLabel = "Finance";
const realLifeCategory: IToolCategory = "real-life";
const realLifeCategoryLabel = "Daily Use";
const timeGlobalCategory: IToolCategory = "time-global";
const timeGlobalCategoryLabel = "Time & Global";
const healthFitnessCategory: IToolCategory = "health-fitness";
const healthFitnessCategoryLabel = "Health & Fitness";
const utilityCategory: IToolCategory = "utility";
const utilityCategoryLabel = "Utility";
const mathEducationCategory: IToolCategory = "math-education";
const mathEducationCategoryLabel = "Math / Education";

export const toolCategories: IToolCategoryDefinition[] = [
	{
		id: textCategory,
		title: "Text Tools",
		description: "Transform, clean, compare, count, sort, reverse, and preview text directly in the browser.",
		path: "/tools/text",
	},
	{
		id: "pdf",
		title: "PDF Tools",
		description: "Merge, split, rotate, reorder, watermark, and preview PDFs.",
		path: "/tools/pdf",
	},
	{
		id: imageCategory,
		title: "Image Tools",
		description: "Resize, crop, compress, convert, rotate, watermark, and filter images.",
		path: "/tools/image",
	},
	{
		id: "developer",
		title: "Developer Tools",
		description: "Format code, generate hashes, decode JWTs, parse URLs, inspect headers, and run browser-safe developer utilities.",
		path: "/tools/developer",
	},
	{
		id: financeCategory,
		title: "Finance Calculators",
		description: "Calculate loan payments, interest, investments, salary breakup, EMI, and more.",
		path: "/tools/finance",
	},
	{
		id: realLifeCategory,
		title: "Daily Use Tools",
		description: "Calculate trip fuel cost, electricity bills, water intake, tips and more.",
		path: "/tools/real-life",
	},
	{
		id: timeGlobalCategory,
		title: "Time & Global Tools",
		description: "Convert time zones, compare dates, plan meetings, count business days, and check leap years.",
		path: "/tools/time-global",
	},
	{
		id: healthFitnessCategory,
		title: "Health & Fitness Tools",
		description: "Calculate BMI, calories, macros, body measurements, training targets, pregnancy dates, and cycle estimates.",
		path: "/tools/health-fitness",
	},
	{
		id: utilityCategory,
		title: "Utility Tools",
		description: "Convert units of length, weight, temperature, area, volume, speed, data storage, energy, pressure and more.",
		path: "/tools/utility",
	},
	{
		id: mathEducationCategory,
		title: "Education and Math Tools",
		description: "Solve ratios, averages, equations, probability, permutations, matrices, geometry, and scientific calculations.",
		path: "/tools/math-education",
	},
];

export const tools: IToolDefinition[] = [
	{
		id: "case-converter",
		slug: "case-converter",
		title: "Case Converter",
		description: "Convert text to uppercase, lowercase, title case, sentence case, and developer-friendly slugs.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/case-converter",
		keywords: ["case", "uppercase", "lowercase", "title", "sentence", "slug"],
		component: lazy(() => import("./text/case-converter")),
	},
	{
		id: "remove-duplicate-lines",
		slug: "remove-duplicate-lines",
		title: "Remove Duplicate Lines",
		description: "Keep the first occurrence of each line and remove repeated lines.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/remove-duplicate-lines",
		keywords: ["duplicate", "lines", "unique", "dedupe"],
		component: lazy(() => import("./text/remove-duplicate-lines")),
	},
	{
		id: "sort-text",
		slug: "sort-text",
		title: "Sort Text",
		description: "Sort lines alphabetically from A to Z or Z to A.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/sort-text",
		keywords: ["sort", "alphabetical", "lines", "az", "za"],
		component: lazy(() => import("./text/sort-text")),
	},
	{
		id: "reverse-text",
		slug: "reverse-text",
		title: "Reverse Text",
		description: "Reverse characters, words, or lines.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/reverse-text",
		keywords: ["reverse", "words", "characters", "lines"],
		component: lazy(() => import("./text/reverse-text")),
	},
	{
		id: "word-character-counter",
		slug: "word-character-counter",
		title: "Word and Character Counter",
		description: "Count words, characters, lines, paragraphs, and estimated reading time.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/word-character-counter",
		keywords: ["counter", "words", "characters", "reading", "stats"],
		component: lazy(() => import("./text/word-character-counter")),
	},
	{
		id: "remove-extra-spaces",
		slug: "remove-extra-spaces",
		title: "Remove Extra Spaces",
		description: "Normalize repeated spaces and blank lines.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/remove-extra-spaces",
		keywords: ["spaces", "blank lines", "trim", "normalize", "cleanup"],
		component: lazy(() => import("./text/remove-extra-spaces")),
	},
	{
		id: "text-diff-checker",
		slug: "text-diff-checker",
		title: "Text Diff Checker",
		description: "Compare two text blocks line by line.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/text-diff-checker",
		keywords: ["diff", "compare", "changes", "lines"],
		component: lazy(() => import("./text/text-diff-checker")),
	},
	{
		id: "image-details",
		slug: "image-details",
		title: "Image Details",
		description: "Preview images, inspect file details, extract color palettes, view EXIF metadata, and pick colors from pixels.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/image-details",
		keywords: ["image", "details", "preview", "metadata", "exif", "color palette", "dominant colors", "eyedropper", "color picker"],
		component: lazy(() => import("./image/image-details")),
	},
	{
		id: "image-to-base64",
		slug: "image-to-base64",
		title: "Image to Base64",
		description: "Convert an image file into a Base64 data URL fully in the browser.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/image-to-base64",
		keywords: ["image", "base64", "data url", "encode", "developer"],
		component: lazy(() => import("./image/image-to-base64")),
	},
	{
		id: "base64-to-image",
		slug: "base64-to-image",
		title: "Base64 to Image",
		description: "Convert a Base64 data URL or raw Base64 string back into a previewable downloadable image.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/base64-to-image",
		keywords: ["base64", "image", "decode", "data url", "download"],
		component: lazy(() => import("./image/base64-to-image")),
	},
	{
		id: "svg-converter",
		slug: "svg-converter",
		title: "SVG Converter",
		description: "Convert raster images to SVG paths with the local VTracer WASM engine and full tracing controls.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/svg-converter",
		keywords: ["svg", "converter", "vtracer", "trace", "vector", "wasm"],
		component: lazy(() => import("./image/svg-converter")),
	},
	{
		id: "resize-image",
		slug: "resize-image",
		title: "Resize Image",
		description: "Resize images by width and height with aspect-ratio lock and high-quality browser processing.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/resize-image",
		keywords: ["image", "resize", "dimensions", "width", "height", "pica"],
		component: lazy(() => import("./image/resize-image")),
	},
	{
		id: "rotate-flip-image",
		slug: "rotate-flip-image",
		title: "Rotate / Flip Image",
		description: "Rotate images by right angles and flip horizontally or vertically in the browser.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/rotate-flip-image",
		keywords: ["image", "rotate", "flip", "mirror", "orientation"],
		component: lazy(() => import("./image/rotate-flip-image")),
	},
	{
		id: "convert-image",
		slug: "convert-image",
		title: "Convert Image Format",
		description: "Convert images to PNG, JPEG, WEBP, or AVIF when supported by the browser.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/convert-image",
		keywords: ["image", "convert", "format", "png", "jpg", "webp", "avif"],
		component: lazy(() => import("./image/convert-image")),
	},
	{
		id: "compress-image",
		slug: "compress-image",
		title: "Compress Image",
		description: "Compress images with quality and target-size controls using browser workers.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/compress-image",
		keywords: ["image", "compress", "quality", "optimize", "web", "size"],
		component: lazy(() => import("./image/compress-image")),
	},
	{
		id: "crop-image",
		slug: "crop-image",
		title: "Crop Image",
		description: "Crop images with draggable preview, zoom, and common aspect ratios.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/crop-image",
		keywords: ["image", "crop", "aspect ratio", "zoom", "trim"],
		component: lazy(() => import("./image/crop-image")),
	},
	{
		id: "image-filters",
		slug: "image-filters",
		title: "Image Filters",
		description: "Apply brightness, contrast, saturation, blur, grayscale, and sepia filters.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/image-filters",
		keywords: ["image", "filters", "brightness", "contrast", "saturation", "blur", "grayscale", "sepia"],
		component: lazy(() => import("./image/image-filters")),
	},
	{
		id: "watermark-image",
		slug: "watermark-image",
		title: "Watermark Image",
		description: "Add a text watermark with position, opacity, color, and size controls.",
		category: imageCategory,
		categoryLabel: imageCategoryLabel,
		path: "/tools/image/watermark-image",
		keywords: ["image", "watermark", "text", "copyright", "overlay"],
		component: lazy(() => import("./image/watermark-image")),
	},
	{
		id: "sip-calculator",
		slug: "sip-calculator",
		title: "SIP Calculator",
		description: "Estimate SIP maturity value, invested amount, and wealth gain with charts.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/sip-calculator",
		keywords: ["sip", "investment", "mutual fund", "monthly", "returns"],
		component: lazy(() => import("./finance/sip-calculator")),
	},
	{
		id: "compound-interest",
		slug: "compound-interest",
		title: "Compound Interest Calculator",
		description: "Calculate maturity amount and compound interest by compounding frequency.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/compound-interest",
		keywords: ["compound", "interest", "maturity", "principal", "rate"],
		component: lazy(() => import("./finance/compound-interest")),
	},
	{
		id: "simple-interest",
		slug: "simple-interest",
		title: "Simple Interest Calculator",
		description: "Calculate simple interest and total amount from principal, rate, and time.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/simple-interest",
		keywords: ["simple", "interest", "principal", "rate", "amount"],
		component: lazy(() => import("./finance/simple-interest")),
	},
	{
		id: "fd-rd-calculator",
		slug: "fd-rd-calculator",
		title: "FD / RD Calculator",
		description: "Estimate fixed deposit or recurring deposit maturity value and interest.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/fd-rd-calculator",
		keywords: ["fd", "rd", "fixed deposit", "recurring deposit", "maturity"],
		component: lazy(() => import("./finance/fd-rd-calculator")),
	},
	{
		id: "loan-eligibility",
		slug: "loan-eligibility",
		title: "Loan Eligibility Calculator",
		description: "Estimate eligible loan amount from income, obligations, interest rate, and tenure.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/loan-eligibility",
		keywords: ["loan", "eligibility", "income", "foir", "emi"],
		component: lazy(() => import("./finance/loan-eligibility")),
	},
	{
		id: "credit-card-payoff",
		slug: "credit-card-payoff",
		title: "Credit Card Payoff Calculator",
		description: "Estimate payoff time, total interest, and balance reduction for credit card debt.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/credit-card-payoff",
		keywords: ["credit card", "payoff", "debt", "apr", "interest"],
		component: lazy(() => import("./finance/credit-card-payoff")),
	},
	{
		id: "salary-breakup",
		slug: "salary-breakup",
		title: "Salary Breakup Calculator",
		description: "Break CTC into salary components, deductions, and estimated in-hand salary.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/salary-breakup",
		keywords: ["salary", "ctc", "in hand", "breakup", "tax", "pf"],
		component: lazy(() => import("./finance/salary-breakup")),
	},
	{
		id: "inflation-calculator",
		slug: "inflation-calculator",
		title: "Inflation Calculator",
		description: "Estimate future cost and purchasing power after inflation.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/inflation-calculator",
		keywords: ["inflation", "future cost", "purchasing power", "price"],
		component: lazy(() => import("./finance/inflation-calculator")),
	},
	{
		id: "discount-calculator",
		slug: "discount-calculator",
		title: "Discount Calculator",
		description: "Calculate sale price, savings, tax, and final payable amount.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/discount-calculator",
		keywords: ["discount", "sale", "price", "tax", "savings"],
		component: lazy(() => import("./finance/discount-calculator")),
	},
	{
		id: "net-worth-calculator",
		slug: "net-worth-calculator",
		title: "Net Worth Calculator",
		description: "Add assets and liabilities to calculate net worth with a visual breakdown.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/net-worth-calculator",
		keywords: ["net worth", "assets", "liabilities", "wealth", "debt"],
		component: lazy(() => import("./finance/net-worth-calculator")),
	},
	{
		id: "emi-amortization",
		slug: "emi-amortization",
		title: "EMI with Amortization Schedule",
		description: "Calculate EMI, total interest, and yearly amortization schedule.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/emi-amortization",
		keywords: ["emi", "amortization", "loan", "schedule", "interest"],
		component: lazy(() => import("./finance/emi-amortization")),
	},
	{
		id: "percentage-profit-margin",
		slug: "percentage-profit-margin",
		title: "Percentage and Profit Margin Calculator",
		description: "Calculate percentage increase or decrease, profit, margin, and markup.",
		category: financeCategory,
		categoryLabel: financeCategoryLabel,
		path: "/tools/finance/percentage-profit-margin",
		keywords: ["percentage", "increase", "decrease", "profit", "margin", "markup"],
		component: lazy(() => import("./finance/percentage-profit-margin")),
	},
	{
		id: "advanced-age",
		slug: "advanced-age",
		title: "Advanced Age Calculator",
		description: "Calculate age in years, months, days, total days, total hours, and next birthday countdown.",
		category: realLifeCategory,
		categoryLabel: realLifeCategoryLabel,
		path: "/tools/real-life/advanced-age",
		keywords: ["age", "birthday", "years", "months", "days", "hours"],
		component: lazy(() => import("./real-life/advanced-age")),
	},
	{
		id: "fuel-cost",
		slug: "fuel-cost",
		title: "Fuel Cost Calculator",
		description: "Estimate trip fuel, total travel cost, cost per kilometer, and per-person split.",
		category: realLifeCategory,
		categoryLabel: realLifeCategoryLabel,
		path: "/tools/real-life/fuel-cost",
		keywords: ["fuel", "trip", "car", "mileage", "travel", "cost"],
		component: lazy(() => import("./real-life/fuel-cost")),
	},
	{
		id: "electricity-bill",
		slug: "electricity-bill",
		title: "Electricity Bill Calculator",
		description: "Calculate electricity bill from units, rate, fixed charges, and tax.",
		category: realLifeCategory,
		categoryLabel: realLifeCategoryLabel,
		path: "/tools/real-life/electricity-bill",
		keywords: ["electricity", "bill", "units", "kwh", "power", "tax"],
		component: lazy(() => import("./real-life/electricity-bill")),
	},
	{
		id: "water-intake",
		slug: "water-intake",
		title: "Water Intake Calculator",
		description: "Estimate daily water intake from weight, activity, climate, and glass size.",
		category: realLifeCategory,
		categoryLabel: realLifeCategoryLabel,
		path: "/tools/real-life/water-intake",
		keywords: ["water", "hydration", "intake", "health", "glasses"],
		component: lazy(() => import("./real-life/water-intake")),
	},
	{
		id: "tip-calculator",
		slug: "tip-calculator",
		title: "Tip Calculator",
		description: "Calculate tip, tax, total bill, and per-person restaurant share.",
		category: realLifeCategory,
		categoryLabel: realLifeCategoryLabel,
		path: "/tools/real-life/tip-calculator",
		keywords: ["tip", "restaurant", "bill", "tax", "split"],
		component: lazy(() => import("./real-life/tip-calculator")),
	},
	{
		id: "split-bill",
		slug: "split-bill",
		title: "Split Bill Calculator",
		description: "Split a bill across people with tax, service, and extra charges.",
		category: realLifeCategory,
		categoryLabel: realLifeCategoryLabel,
		path: "/tools/real-life/split-bill",
		keywords: ["split", "bill", "friends", "restaurant", "share"],
		component: lazy(() => import("./real-life/split-bill")),
	},
	{
		id: "timezone-converter",
		slug: "timezone-converter",
		title: "Timezone Converter",
		description: "Convert a date and time from one timezone to another with UTC offsets.",
		category: timeGlobalCategory,
		categoryLabel: timeGlobalCategoryLabel,
		path: "/tools/time-global/timezone-converter",
		keywords: ["timezone", "time zone", "convert", "utc", "gmt", "offset"],
		component: lazy(() => import("./time-global/timezone-converter")),
	},
	{
		id: "world-clock",
		slug: "world-clock",
		title: "World Clock",
		description: "Track live local times across multiple cities and time zones.",
		category: timeGlobalCategory,
		categoryLabel: timeGlobalCategoryLabel,
		path: "/tools/time-global/world-clock",
		keywords: ["world clock", "time", "timezone", "city", "live clock"],
		component: lazy(() => import("./time-global/world-clock")),
	},
	{
		id: "meeting-planner",
		slug: "meeting-planner",
		title: "Meeting Planner",
		description: "Plan a meeting across multiple timezones and check local working-hour fit.",
		category: timeGlobalCategory,
		categoryLabel: timeGlobalCategoryLabel,
		path: "/tools/time-global/meeting-planner",
		keywords: ["meeting", "planner", "timezone", "schedule", "calendar", "work hours"],
		component: lazy(() => import("./time-global/meeting-planner")),
	},
	{
		id: "date-difference-calculator",
		slug: "date-difference-calculator",
		title: "Date Difference Calculator",
		description: "Calculate calendar difference, total days, weeks, and inclusive day count between two dates.",
		category: timeGlobalCategory,
		categoryLabel: timeGlobalCategoryLabel,
		path: "/tools/time-global/date-difference-calculator",
		keywords: ["date", "difference", "days between", "weeks", "calendar"],
		component: lazy(() => import("./time-global/date-difference-calculator")),
	},
	{
		id: "business-days-calculator",
		slug: "business-days-calculator",
		title: "Business Days Calculator",
		description: "Count working days between dates while excluding weekends and optional holidays.",
		category: timeGlobalCategory,
		categoryLabel: timeGlobalCategoryLabel,
		path: "/tools/time-global/business-days-calculator",
		keywords: ["business days", "working days", "weekends", "holidays", "date"],
		component: lazy(() => import("./time-global/business-days-calculator")),
	},
	{
		id: "leap-year-checker",
		slug: "leap-year-checker",
		title: "Leap Year Checker",
		description: "Check whether a year is a leap year and find nearby leap years.",
		category: timeGlobalCategory,
		categoryLabel: timeGlobalCategoryLabel,
		path: "/tools/time-global/leap-year-checker",
		keywords: ["leap year", "year", "february", "calendar"],
		component: lazy(() => import("./time-global/leap-year-checker")),
	},
	{
		id: "bmi-calculator",
		slug: "bmi-calculator",
		title: "BMI Calculator",
		description: "Calculate body mass index, BMI category, and healthy weight range.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/bmi-calculator",
		keywords: ["bmi", "body mass index", "weight", "height", "healthy weight"],
		component: lazy(() => import("./health-fitness/bmi-calculator")),
	},
	{
		id: "calorie-calculator",
		slug: "calorie-calculator",
		title: "Calorie Calculator",
		description: "Estimate daily calories from BMR, activity level, and fitness goal.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/calorie-calculator",
		keywords: ["calorie", "calories", "maintenance", "diet", "weight loss", "weight gain"],
		component: lazy(() => import("./health-fitness/calorie-calculator")),
	},
	{
		id: "body-fat-calculator",
		slug: "body-fat-calculator",
		title: "Body Fat Calculator",
		description: "Estimate body fat percentage, fat mass, and lean mass using circumference measurements.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/body-fat-calculator",
		keywords: ["body fat", "fat percentage", "navy", "waist", "neck", "hip"],
		component: lazy(() => import("./health-fitness/body-fat-calculator")),
	},
	{
		id: "bmr-calculator",
		slug: "bmr-calculator",
		title: "BMR Calculator",
		description: "Calculate basal metabolic rate and estimated calories by activity level.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/bmr-calculator",
		keywords: ["bmr", "basal metabolic rate", "metabolism", "calories"],
		component: lazy(() => import("./health-fitness/bmr-calculator")),
	},
	{
		id: "ideal-weight-calculator",
		slug: "ideal-weight-calculator",
		title: "Ideal Weight Calculator",
		description: "Compare ideal body weight estimates from Devine, Robinson, and Miller formulas.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/ideal-weight-calculator",
		keywords: ["ideal weight", "body weight", "devine", "robinson", "miller"],
		component: lazy(() => import("./health-fitness/ideal-weight-calculator")),
	},
	{
		id: "pace-calculator",
		slug: "pace-calculator",
		title: "Pace Calculator",
		description: "Calculate running pace, speed, mile pace, and race projections.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/pace-calculator",
		keywords: ["pace", "running", "speed", "5k", "kilometer", "mile"],
		component: lazy(() => import("./health-fitness/pace-calculator")),
	},
	{
		id: "army-body-fat-calculator",
		slug: "army-body-fat-calculator",
		title: "Army Body Fat Calculator",
		description: "Estimate Army-style body fat percentage and compare it with reference screening limits.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/army-body-fat-calculator",
		keywords: ["army", "body fat", "military", "waist", "neck", "fitness"],
		component: lazy(() => import("./health-fitness/army-body-fat-calculator")),
	},
	{
		id: "lean-body-mass-calculator",
		slug: "lean-body-mass-calculator",
		title: "Lean Body Mass Calculator",
		description: "Estimate lean body mass from body fat percentage and Boer formula.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/lean-body-mass-calculator",
		keywords: ["lean body mass", "lbm", "fat mass", "body composition", "boer"],
		component: lazy(() => import("./health-fitness/lean-body-mass-calculator")),
	},
	{
		id: "healthy-weight-calculator",
		slug: "healthy-weight-calculator",
		title: "Healthy Weight Calculator",
		description: "Find the healthy BMI weight range for a height and compare current weight.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/healthy-weight-calculator",
		keywords: ["healthy weight", "bmi range", "weight range", "height"],
		component: lazy(() => import("./health-fitness/healthy-weight-calculator")),
	},
	{
		id: "calories-burned-calculator",
		slug: "calories-burned-calculator",
		title: "Calories Burned Calculator",
		description: "Estimate calories burned during activities using MET values, weight, and duration.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/calories-burned-calculator",
		keywords: ["calories burned", "exercise", "met", "running", "cycling", "workout"],
		component: lazy(() => import("./health-fitness/calories-burned-calculator")),
	},
	{
		id: "one-rep-max-calculator",
		slug: "one-rep-max-calculator",
		title: "One Rep Max Calculator",
		description: "Estimate one-rep max from lifted weight and repetitions, with percentage training loads.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/one-rep-max-calculator",
		keywords: ["one rep max", "1rm", "strength", "lifting", "epley", "brzycki"],
		component: lazy(() => import("./health-fitness/one-rep-max-calculator")),
	},
	{
		id: "target-heart-rate-calculator",
		slug: "target-heart-rate-calculator",
		title: "Target Heart Rate Calculator",
		description: "Calculate target heart-rate zones using age, resting heart rate, and intensity range.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/target-heart-rate-calculator",
		keywords: ["target heart rate", "heart rate", "bpm", "karvonen", "training zone"],
		component: lazy(() => import("./health-fitness/target-heart-rate-calculator")),
	},
	{
		id: "macro-calculator",
		slug: "macro-calculator",
		title: "Macro Calculator",
		description: "Split daily calories into protein, carbohydrates, and fat based on a macro goal.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/macro-calculator",
		keywords: ["macros", "protein", "carbs", "fat", "nutrition", "diet"],
		component: lazy(() => import("./health-fitness/macro-calculator")),
	},
	{
		id: "carbohydrate-calculator",
		slug: "carbohydrate-calculator",
		title: "Carbohydrate Calculator",
		description: "Calculate daily carbohydrate grams from calories and carbohydrate percentage.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/carbohydrate-calculator",
		keywords: ["carbohydrate", "carbs", "nutrition", "grams", "calories"],
		component: lazy(() => import("./health-fitness/carbohydrate-calculator")),
	},
	{
		id: "protein-calculator",
		slug: "protein-calculator",
		title: "Protein Calculator",
		description: "Estimate daily protein target from body weight and fitness goal.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/protein-calculator",
		keywords: ["protein", "nutrition", "muscle", "grams", "body weight"],
		component: lazy(() => import("./health-fitness/protein-calculator")),
	},
	{
		id: "fat-intake-calculator",
		slug: "fat-intake-calculator",
		title: "Fat Intake Calculator",
		description: "Calculate daily fat grams from calories and desired fat percentage.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/fat-intake-calculator",
		keywords: ["fat intake", "dietary fat", "nutrition", "grams", "calories"],
		component: lazy(() => import("./health-fitness/fat-intake-calculator")),
	},
	{
		id: "tdee-calculator",
		slug: "tdee-calculator",
		title: "TDEE Calculator",
		description: "Calculate total daily energy expenditure and calorie targets for loss or gain.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/tdee-calculator",
		keywords: ["tdee", "energy expenditure", "calories", "bmr", "activity"],
		component: lazy(() => import("./health-fitness/tdee-calculator")),
	},
	{
		id: "gfr-calculator",
		slug: "gfr-calculator",
		title: "GFR Calculator",
		description: "Estimate eGFR from age, sex, and serum creatinine using the CKD-EPI 2021 equation.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/gfr-calculator",
		keywords: ["gfr", "egfr", "kidney", "creatinine", "ckd epi"],
		component: lazy(() => import("./health-fitness/gfr-calculator")),
	},
	{
		id: "body-type-calculator",
		slug: "body-type-calculator",
		title: "Body Type Calculator",
		description: "Estimate body shape and waist-hip ratio from chest, waist, and hip measurements.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/body-type-calculator",
		keywords: ["body type", "body shape", "waist hip ratio", "measurements"],
		component: lazy(() => import("./health-fitness/body-type-calculator")),
	},
	{
		id: "body-surface-area-calculator",
		slug: "body-surface-area-calculator",
		title: "Body Surface Area Calculator",
		description: "Calculate body surface area using Mosteller, Du Bois, and Haycock formulas.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/body-surface-area-calculator",
		keywords: ["body surface area", "bsa", "mosteller", "du bois", "haycock"],
		component: lazy(() => import("./health-fitness/body-surface-area-calculator")),
	},
	{
		id: "bac-calculator",
		slug: "bac-calculator",
		title: "BAC Calculator",
		description: "Estimate blood alcohol concentration from drinks, ABV, body weight, sex, and time.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/bac-calculator",
		keywords: ["bac", "blood alcohol", "alcohol", "widmark", "drinks"],
		component: lazy(() => import("./health-fitness/bac-calculator")),
	},
	{
		id: "pregnancy-calculator",
		slug: "pregnancy-calculator",
		title: "Pregnancy Calculator",
		description: "Estimate due date, gestational age, trimester, and days remaining from last period.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/pregnancy-calculator",
		keywords: ["pregnancy", "gestational age", "trimester", "due date", "lmp"],
		component: lazy(() => import("./health-fitness/pregnancy-calculator")),
	},
	{
		id: "pregnancy-weight-gain-calculator",
		slug: "pregnancy-weight-gain-calculator",
		title: "Pregnancy Weight Gain Calculator",
		description: "Compare pregnancy weight gain with broad recommended ranges by BMI and pregnancy type.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/pregnancy-weight-gain-calculator",
		keywords: ["pregnancy weight", "weight gain", "pregnancy", "bmi", "twins"],
		component: lazy(() => import("./health-fitness/pregnancy-weight-gain-calculator")),
	},
	{
		id: "pregnancy-conception-calculator",
		slug: "pregnancy-conception-calculator",
		title: "Pregnancy Conception Calculator",
		description: "Estimate conception date, fertile window, and LMP from a pregnancy due date.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/pregnancy-conception-calculator",
		keywords: ["pregnancy conception", "conception date", "due date", "fertile window", "lmp"],
		component: lazy(() => import("./health-fitness/pregnancy-conception-calculator")),
	},
	{
		id: "due-date-calculator",
		slug: "due-date-calculator",
		title: "Due Date Calculator",
		description: "Estimate pregnancy due date and conception date from last period and cycle length.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/due-date-calculator",
		keywords: ["due date", "pregnancy", "lmp", "conception", "cycle length"],
		component: lazy(() => import("./health-fitness/due-date-calculator")),
	},
	{
		id: "ovulation-calculator",
		slug: "ovulation-calculator",
		title: "Ovulation Calculator",
		description: "Estimate ovulation date, fertile window, and next period from cycle details.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/ovulation-calculator",
		keywords: ["ovulation", "fertile window", "cycle", "period", "luteal phase"],
		component: lazy(() => import("./health-fitness/ovulation-calculator")),
	},
	{
		id: "conception-calculator",
		slug: "conception-calculator",
		title: "Conception Calculator",
		description: "Estimate likely conception timing, fertile window, and possible due date from cycle data.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/conception-calculator",
		keywords: ["conception", "fertile window", "ovulation", "pregnancy", "cycle"],
		component: lazy(() => import("./health-fitness/conception-calculator")),
	},
	{
		id: "period-calculator",
		slug: "period-calculator",
		title: "Period Calculator",
		description: "Estimate next period dates, ovulation, and fertile window from cycle length.",
		category: healthFitnessCategory,
		categoryLabel: healthFitnessCategoryLabel,
		path: "/tools/health-fitness/period-calculator",
		keywords: ["period", "menstrual cycle", "cycle", "ovulation", "fertile window"],
		component: lazy(() => import("./health-fitness/period-calculator")),
	},
	{
		id: "length-converter",
		slug: "length-converter",
		title: "Length Converter",
		description: "Convert meters, kilometers, miles, feet, inches, yards, and more.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/length-converter",
		keywords: ["length", "meter", "kilometer", "mile", "feet", "inch"],
		component: lazy(() => import("./utility/length-converter")),
	},
	{
		id: "weight-converter",
		slug: "weight-converter",
		title: "Weight Converter",
		description: "Convert kilograms, grams, pounds, ounces, tonnes, and stone.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/weight-converter",
		keywords: ["weight", "mass", "kg", "pound", "ounce", "tonne"],
		component: lazy(() => import("./utility/weight-converter")),
	},
	{
		id: "temperature-converter",
		slug: "temperature-converter",
		title: "Temperature Converter",
		description: "Convert Celsius, Fahrenheit, and Kelvin temperatures.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/temperature-converter",
		keywords: ["temperature", "celsius", "fahrenheit", "kelvin"],
		component: lazy(() => import("./utility/temperature-converter")),
	},
	{
		id: "area-converter",
		slug: "area-converter",
		title: "Area Converter",
		description: "Convert square feet, square meters, acres, hectares, square yards, and more.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/area-converter",
		keywords: ["area", "square feet", "square meter", "acre", "hectare"],
		component: lazy(() => import("./utility/area-converter")),
	},
	{
		id: "volume-converter",
		slug: "volume-converter",
		title: "Volume Converter",
		description: "Convert liters, milliliters, cubic meters, gallons, cups, and fluid ounces.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/volume-converter",
		keywords: ["volume", "liter", "milliliter", "gallon", "cup", "cubic meter"],
		component: lazy(() => import("./utility/volume-converter")),
	},
	{
		id: "speed-converter",
		slug: "speed-converter",
		title: "Speed Converter",
		description: "Convert km/h, mph, m/s, knots, and ft/s speed units.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/speed-converter",
		keywords: ["speed", "kmh", "mph", "meter per second", "knot"],
		component: lazy(() => import("./utility/speed-converter")),
	},
	{
		id: "data-storage-converter",
		slug: "data-storage-converter",
		title: "Data Storage Converter",
		description: "Convert bits, bytes, KB, MB, GB, TB, KiB, MiB, GiB, and TiB.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/data-storage-converter",
		keywords: ["data", "storage", "mb", "gb", "tb", "byte", "bit"],
		component: lazy(() => import("./utility/data-storage-converter")),
	},
	{
		id: "internet-speed-converter",
		slug: "internet-speed-converter",
		title: "Internet Speed Converter",
		description: "Convert Mbps to MBps and compare bit-per-second and byte-per-second rates.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/internet-speed-converter",
		keywords: ["internet", "speed", "mbps", "mbps to mbps", "mbps", "download"],
		component: lazy(() => import("./utility/internet-speed-converter")),
	},
	{
		id: "energy-converter",
		slug: "energy-converter",
		title: "Energy Converter",
		description: "Convert joules, calories, kilocalories, watt-hours, kWh, BTU, and electronvolts.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/energy-converter",
		keywords: ["energy", "joule", "calorie", "kwh", "btu", "watt hour"],
		component: lazy(() => import("./utility/energy-converter")),
	},
	{
		id: "pressure-converter",
		slug: "pressure-converter",
		title: "Pressure Converter",
		description: "Convert pascal, kPa, MPa, bar, millibar, psi, atmosphere, and torr.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/pressure-converter",
		keywords: ["pressure", "pascal", "bar", "psi", "atm", "torr"],
		component: lazy(() => import("./utility/pressure-converter")),
	},
	{
		id: "land-area-converter",
		slug: "land-area-converter",
		title: "Land Area Converter",
		description: "Convert Indian land units like bigha, gaj, biswa, katha, marla, kanal, acre, and hectare.",
		category: utilityCategory,
		categoryLabel: utilityCategoryLabel,
		path: "/tools/utility/land-area-converter",
		keywords: ["land", "area", "bigha", "gaj", "katha", "marla", "acre"],
		component: lazy(() => import("./utility/land-area-converter")),
	},
	{
		id: "ratio-calculator",
		slug: "ratio-calculator",
		title: "Ratio Calculator",
		description: "Simplify ratios and convert ratios into decimal and percentage form.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/ratio-calculator",
		keywords: ["ratio", "proportion", "simplify", "percent"],
		component: lazy(() => import("./math-education/ratio-calculator")),
	},
	{
		id: "average-calculator",
		slug: "average-calculator",
		title: "Average and Weighted Average",
		description: "Calculate arithmetic average, weighted average, count, and sum.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/average-calculator",
		keywords: ["average", "weighted average", "mean", "sum"],
		component: lazy(() => import("./math-education/average-calculator")),
	},
	{
		id: "scientific-calculator",
		slug: "scientific-calculator",
		title: "Basic and Scientific Calculator",
		description: "Evaluate arithmetic, parentheses, trig, logs, exponents, radians/degrees, constants, and memory operations.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/scientific-calculator",
		keywords: ["calculator", "scientific", "trig", "logs", "exponents", "memory"],
		component: lazy(() => import("./math-education/scientific-calculator")),
	},
	{
		id: "lcm-hcf-calculator",
		slug: "lcm-hcf-calculator",
		title: "LCM / HCF Calculator",
		description: "Find least common multiple and highest common factor for a list of numbers.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/lcm-hcf-calculator",
		keywords: ["lcm", "hcf", "gcd", "factor", "multiple"],
		component: lazy(() => import("./math-education/lcm-hcf-calculator")),
	},
	{
		id: "prime-checker",
		slug: "prime-checker",
		title: "Prime Number Checker",
		description: "Check whether a number is prime and list its factors.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/prime-checker",
		keywords: ["prime", "number", "factors", "divisors"],
		component: lazy(() => import("./math-education/prime-checker")),
	},
	{
		id: "factorial-calculator",
		slug: "factorial-calculator",
		title: "Factorial Calculator",
		description: "Calculate n factorial and digit count using BigInt.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/factorial-calculator",
		keywords: ["factorial", "bigint", "n factorial", "permutation"],
		component: lazy(() => import("./math-education/factorial-calculator")),
	},
	{
		id: "quadratic-solver",
		slug: "quadratic-solver",
		title: "Quadratic Equation Solver",
		description: "Solve ax^2 + bx + c = 0 with real or complex roots.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/quadratic-solver",
		keywords: ["quadratic", "equation", "roots", "discriminant"],
		component: lazy(() => import("./math-education/quadratic-solver")),
	},
	{
		id: "probability-calculator",
		slug: "probability-calculator",
		title: "Probability Calculator",
		description: "Calculate independent event probabilities like A and B, A or B, and not A.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/probability-calculator",
		keywords: ["probability", "event", "independent", "and", "or"],
		component: lazy(() => import("./math-education/probability-calculator")),
	},
	{
		id: "permutation-combination",
		slug: "permutation-combination",
		title: "Permutation and Combination",
		description: "Calculate nPr and nCr values from n and r.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/permutation-combination",
		keywords: ["permutation", "combination", "npr", "ncr", "choose"],
		component: lazy(() => import("./math-education/permutation-combination")),
	},
	{
		id: "matrix-calculator",
		slug: "matrix-calculator",
		title: "Matrix Calculator",
		description: "Add, subtract, multiply, transpose, and calculate 2x2 determinant for matrices.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/matrix-calculator",
		keywords: ["matrix", "multiply", "transpose", "determinant", "linear algebra"],
		component: lazy(() => import("./math-education/matrix-calculator")),
	},
	{
		id: "geometry-calculator",
		slug: "geometry-calculator",
		title: "Geometry Calculators",
		description: "Calculate circle area, triangle area, rectangle area, and common volumes.",
		category: mathEducationCategory,
		categoryLabel: mathEducationCategoryLabel,
		path: "/tools/math-education/geometry-calculator",
		keywords: ["geometry", "circle", "triangle", "area", "volume", "sphere", "cylinder"],
		component: lazy(() => import("./math-education/geometry-calculator")),
	},
	{
		id: "regex-tester",
		slug: "regex-tester",
		title: "Regex Tester",
		description: "Test regular expressions and inspect matches in text.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/regex-tester",
		keywords: ["regex", "regexp", "matches", "pattern"],
		component: lazy(() => import("./developer/regex-tester")),
	},
	{
		id: "json-formatter",
		slug: "json-formatter",
		title: "JSON Formatter",
		description: "Validate, format, and minify JSON.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/json-formatter",
		keywords: ["json", "formatter", "validator", "minify", "pretty"],
		component: lazy(() => import("./developer/json-formatter")),
	},
	{
		id: "xml-formatter",
		slug: "xml-formatter",
		title: "XML Formatter",
		description: "Validate and format XML with browser parsing APIs.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/xml-formatter",
		keywords: ["xml", "formatter", "validator", "pretty"],
		component: lazy(() => import("./developer/xml-formatter")),
	},
	{
		id: "csv-json-converter",
		slug: "csv-json-converter",
		title: "CSV and JSON Converter",
		description: "Convert CSV to JSON and JSON arrays back to CSV.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/csv-json-converter",
		keywords: ["csv", "json", "convert", "table", "data"],
		component: lazy(() => import("./developer/csv-json-converter")),
	},
	{
		id: "base64-codec",
		slug: "base64-codec",
		title: "Base64 Encode Decode",
		description: "Encode text to Base64 or decode Base64 back to text.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/base64-codec",
		keywords: ["base64", "encode", "decode"],
		component: lazy(() => import("./developer/base64-codec")),
	},
	{
		id: "url-codec",
		slug: "url-codec",
		title: "URL Encode Decode",
		description: "Encode or decode URL components safely in the browser.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/url-codec",
		keywords: ["url", "uri", "encode", "decode", "percent"],
		component: lazy(() => import("./developer/url-codec")),
	},
	{
		id: "html-codec",
		slug: "html-codec",
		title: "HTML Encode Decode",
		description: "Encode HTML entities or decode entity strings back to text.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/html-codec",
		keywords: ["html", "entities", "escape", "encode", "decode"],
		component: lazy(() => import("./developer/html-codec")),
	},
	{
		id: "code-formatter",
		slug: "code-formatter",
		title: "Code Formatter",
		description: "Format JavaScript, TypeScript, JSON, HTML, and CSS with Prettier.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/code-formatter",
		keywords: ["code", "formatter", "prettier", "javascript", "typescript", "json", "html", "css"],
		component: lazy(() => import("./developer/code-formatter")),
	},
	{
		id: "uuid-generator",
		slug: "uuid-generator",
		title: "UUID Generator",
		description: "Generate one or many UUID v4 values in the browser.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/uuid-generator",
		keywords: ["uuid", "guid", "generator", "random"],
		component: lazy(() => import("./developer/uuid-generator")),
	},
	{
		id: "password-generator",
		slug: "password-generator",
		title: "Password Generator",
		description: "Generate secure random passwords with configurable length and character sets.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/password-generator",
		keywords: ["password", "generator", "random", "secure"],
		component: lazy(() => import("./developer/password-generator")),
	},
	{
		id: "hash-generator",
		slug: "hash-generator",
		title: "Hash Generator",
		description: "Generate SHA256 or MD5 hashes using crypto-js.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/hash-generator",
		keywords: ["hash", "sha256", "md5", "crypto", "checksum"],
		component: lazy(() => import("./developer/hash-generator")),
	},
	{
		id: "jwt-decoder",
		slug: "jwt-decoder",
		title: "JWT Decoder",
		description: "Decode JWT header and payload segments without sending tokens to a server.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/jwt-decoder",
		keywords: ["jwt", "token", "decoder", "base64url"],
		component: lazy(() => import("./developer/jwt-decoder")),
	},
	{
		id: "color-picker",
		slug: "color-picker",
		title: "Color Picker",
		description: "Pick colors and copy HEX, RGB, HSL, or CSS variable values.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/color-picker",
		keywords: ["color", "picker", "hex", "rgb", "hsl", "css"],
		component: lazy(() => import("./developer/color-picker")),
	},
	{
		id: "cron-generator",
		slug: "cron-generator",
		title: "Cron Generator",
		description: "Create common cron expressions and edit custom schedules.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/cron-generator",
		keywords: ["cron", "schedule", "generator", "jobs"],
		component: lazy(() => import("./developer/cron-generator")),
	},
	{
		id: "url-parser",
		slug: "url-parser",
		title: "URL Parser",
		description: "Split URLs into protocol, host, path, hash, and query string parts.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/url-parser",
		keywords: ["url", "parser", "query", "string", "splitter"],
		component: lazy(() => import("./developer/url-parser")),
	},
	{
		id: "http-header-formatter",
		slug: "http-header-formatter",
		title: "HTTP Header Formatter",
		description: "Format raw HTTP headers into readable JSON.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/http-header-formatter",
		keywords: ["http", "headers", "formatter", "json"],
		component: lazy(() => import("./developer/http-header-formatter")),
	},
	{
		id: "api-response-time-calculator",
		slug: "api-response-time-calculator",
		title: "API Response Time Calculator",
		description: "Send a URL or cURL command with axios and measure API status, response time, headers, size, and body.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/api-response-time-calculator",
		keywords: ["api", "response", "time", "latency", "duration", "curl", "axios", "postman", "reqbin", "performance"],
		component: lazy(() => import("./developer/api-response-time-calculator")),
	},
	{
		id: "aes-encrypt-decrypt",
		slug: "aes-encrypt-decrypt",
		title: "AES Encrypt Decrypt",
		description: "Encrypt or decrypt text with AES using crypto-js.",
		category: developerCategory,
		categoryLabel: developerCategoryLabel,
		path: "/tools/developer/aes-encrypt-decrypt",
		keywords: ["aes", "encrypt", "decrypt", "crypto", "secret"],
		component: lazy(() => import("./developer/aes-encrypt-decrypt")),
	},
	{
		id: "markdown-preview",
		slug: "markdown-preview",
		title: "Markdown Preview",
		description: "Preview safe Markdown output without sending content to a server.",
		category: textCategory,
		categoryLabel: textCategoryLabel,
		path: "/tools/text/markdown-preview",
		keywords: ["markdown", "preview", "md", "render"],
		component: lazy(() => import("./text/markdown-preview")),
	},
];

export const getCategoryById = (categoryId: string | undefined) => toolCategories.find((category) => category.id === categoryId);

export const getToolsByCategory = (categoryId: string | undefined) => tools.filter((tool) => tool.category === categoryId);

export const getToolByRoute = (categoryId: string | undefined, slug: string | undefined) =>
	tools.find((tool) => tool.category === categoryId && tool.slug === slug);

export const searchTools = (query: string) => {
	const normalizedQuery = query.trim().toLowerCase();

	if (!normalizedQuery) {
		return tools;
	}

	return tools.filter((tool) =>
		[tool.title, tool.description, tool.categoryLabel, ...tool.keywords].join(" ").toLowerCase().includes(normalizedQuery),
	);
};
